### PR TITLE
rebase moo on master, fix things, merge to master.

### PR DESCRIPTION
**Pull request by dams**
As discussed per email, this is a CPANPR challenge PR. I basically only rebase, fixed stuff, until local tests pass. feedback welcome

### CODE REVIEW

**Comment by mrallen1** [comment]
Considering moving the prereq to Moo 2. Thoughts on that?  I don't have a lot of direct experience with it, but I like that the new strictures module has selected warnings non-fatalized.

**Comment by mrallen1** [comment]
Also - thank you so much 🍬 Really appreciate you stepping in to do this.

**Comment by dams** [comment]
No problem.  So yes you either want Moo 2 or at least use Moo::Lax that I wrote because of the stricture craziness... But yes Moo2 is good, no issues or backward compat problem, so I recommend depending on it.

**Comment by mrallen1** [comment]
Yeah I think Moo 2 is the way to go. Moo 1 fatalizes too aggressively which is why I switched to Moo::Lax for many other of my projects. I ought to switch back to Moo 2 on those some day :)

**Comment by mrallen1** [comment]
Thank you so much for this PR! I appreciate the time and effort you spent on it even though I can't or maybe shouldn't merge it.

**Pull request closed without merging**
