### PR TITLE
added network interfaces attributes into describe_instances

### PR DESCRIPTION
**Pull request by tsiganenok**
Hi all, 

Added new class for network interfaces and wrote some code in order to use in inside describe_instances method. Would like to implement methods which will allow to replace security groups later.

### CODE REVIEW

**Comment by mrallen1** [comment]
Thanks for the patch. 

At first blush, this looks good to me - but I would appreciate if you'd tell your editor to stop stripping whitespace at the end of lines. Makes the diffs for this PR huge when it's really quite a modest set of changes.

**Comment by tsiganenok** [comment]
Fixed, should be much better now :)

**Comment by mrallen1** [comment]
Many thanks.

**Comment by tsiganenok** [comment]
When creating new instance, it's network interface description is empty for some reason, this will cause a fail. Last commit fixes it.

**Comment by mrallen1** [comment]
:+1: Thanks!

**Pull request merged**
